services:
  sems-website:
    build: .
    container_name: sems-ndis-website
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - sems-network

networks:
  sems-network:
    driver: bridge
